eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            label: master
            server:
                git:
                    searchPaths: /config
                    uri: https://gitee.com/endex/springcloudlearning
    rabbitmq:
        host: localhost
        port: 5672
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: hystrix.stream,refresh,bus-refresh
