spring:
  datasource:
    url: jdbc:mysql://104.153.97.114:3306/springcloud?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: ming123
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  application:
    name: ace-trace
   #zipkin数据保存到数据库中需要进行如下配置
   #表示当前程序不使用sleuth
  sleuth:
    enabled: true
   #表示zipkin数据存储方式是mysql

zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: 127.0.0.1
      port: 5672
      password: guest
      username: guest
      queue: zipkin
server:
  port: 9411

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://localhost:8761/eureka/
