eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
spring:
    redis:
        database: 5
        host: 52.193.160.92
        port: 6379